### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [luckyjrocks/prj-rev-bwfs-dasmoto#5]
Simplify! Consider using locally stored images in your project as this is best practice for production code and will allow your page to load faster.  To do this you would create a new `images` folder inside your `resources` folder, like this:   
![screen shot 2018-01-07 at 9 50 24 pm](https://user-images.githubusercontent.com/11949479/34662248-06dd7fe2-f404-11e7-816d-5cf57c4b961b.png)

Example: https://github.com/luckyjrocks/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L11

Then save the images you are using in your project to the new folder and use your `<img>` tags like this: `<img src="./resources/images/hacksaw.jpeg" alt="hacksaw paint brushes">`. Also, be sure to use descriptive `alt` attributes for your `<img>` elements (see above for example). This is best practice and helps make your site more accessible!

**Comment by luckyjrocks** [comment]
I don't quite understand how to save the images I'm using into the images folder that I created. Could you help with that?
